// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkCyJdVAgVbeN8AL4cO2wMRHpbYniIlcI',
    appId: '1:1053582686319:web:0ec1d08c432d4cc2faf59a',
    messagingSenderId: '1053582686319',
    projectId: 'flutter-chat-app-b59b4',
    authDomain: 'flutter-chat-app-b59b4.firebaseapp.com',
    storageBucket: 'flutter-chat-app-b59b4.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBv_qfo8zeUGWlt0DjXSTs7hGfYobXOX8w',
    appId: '1:1053582686319:android:28d5e08fef562240faf59a',
    messagingSenderId: '1053582686319',
    projectId: 'flutter-chat-app-b59b4',
    storageBucket: 'flutter-chat-app-b59b4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_WSb_an0li10vunXrugeWejGD4lbDbmc',
    appId: '1:1053582686319:ios:4c740ca53f0ca918faf59a',
    messagingSenderId: '1053582686319',
    projectId: 'flutter-chat-app-b59b4',
    storageBucket: 'flutter-chat-app-b59b4.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_WSb_an0li10vunXrugeWejGD4lbDbmc',
    appId: '1:1053582686319:ios:f00bf9da7634b41efaf59a',
    messagingSenderId: '1053582686319',
    projectId: 'flutter-chat-app-b59b4',
    storageBucket: 'flutter-chat-app-b59b4.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
